<?xml version="1.0"?>
<package format="3">
  <name>s_slam_simulation</name>
  <version>0.1.0</version>
  <description>
    Simulation assets and launch files for the s-slam system.
  </description>
  <maintainer email="chenqixian428106@gmail.com">s-slam</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ros2launch</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
